name: 'write-good'
description: 'run write-good english prose linter on all markdown files in a repo'
author: 'Joshua LaBelle'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'blue'
