on:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Run the custom write-good action
        uses: jdlabelle/write-good-action@inputs_feature
